---
- name: Creacion y despliegue de contenedor
  hosts: localhost

  vars:
   - repositorio_dockerfile: "/home/desarrollo1/dockerfile/Dockerfile"

   - directorio_dockerfile: "/home/desarrollo1/dockerfile"

   - Nom_imagen: "jboss/wildfly-admin-demo"

   - Nom_cont: "wildfly"

   - user: "Admin"

   - password: "Admin2020"   

  tasks:

   - name: Crear dockerfile
     file:
       path: "{{ repositorio_dockerfile }}"
       state: touch

   - name: dockerfile fase 1
     lineinfile:
       path: "{{ repositorio_dockerfile }}"
       line: 'FROM jboss/wildfly:23.0.0.Final'

   - name: dockerfile fase 2
     lineinfile:
       path: "{{ repositorio_dockerfile }}"
       insertafter: '^#Final '
       line: 'RUN /opt/jboss/wildfly/bin/add-user.sh "{{ user }}" "{{ password }}" --silent'

   - name: dockerfile fase 3
     lineinfile:
       path: "{{ repositorio_dockerfile }}"
       insertafter: '^#silent '
       line: 'CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]'

   - name: Construir Imagen
     command: docker build --tag="{{ Nom_imagen }}" .
     args:
         chdir: "{{ directorio_dockerfile }}"

   - name: Construir Contenedor
     command: docker run -p 49154:8080 -p 49156:9990 -d --name "{{ Nom_cont }}" -it "{{ Nom_imagen }}"
     args:
         chdir: /home/desarrollo1
