---
- name: Clon Git
  hosts: localhost
  sudo: yes
  
  vars:
   - repositorio: "https://github.com/abcnick/Prueba-pipeline.git"
   - rama: "master"
   - proy_codigo: "/home/ubuntu/dockerfile"

  tasks:

   - name: Clone Repo
     git:
       repo: "{{ repositorio }}"
       version: "{{ rama }}"
       dest: "{{ proy_codigo }}"

   - name: Last Commit
     command: git log -1
     register: infocommit
     args:
       chdir: "{{ proy_codigo }}"

   - name: Mensaje Commit
     debug: var=infocommit.stdout_lines
